### ISSUE TITLE
`np.random.uniform` instead of `np.random.normal`?

### ISSUE THREAD

**Issue by youheiakimoto** [uclaacmai/Generative-Adversarial-Network-Tutorial#10]
`np.random.normal(-1, 1, size)` is used in several places to produce random variables in [0, 1], but shouldn't it be `np.random.uniform(-1, 1, size)`. The first two arguments of `normal` are the mean and the std.

**Comment by rohan-varma** [comment]
Thanks for noticing this! It is fixed in https://github.com/uclaacmai/Generative-Adversarial-Network-Tutorial/pull/11.
